feat: 更新 symfony 設定，加快效能表現

diff --git a/php/dockerfile b/php/dockerfile
--- a/php/dockerfile
+++ b/php/dockerfile
@@ -23,11 +23,25 @@ RUN pecl install xdebug
 COPY ./php.ini $PHP_INI_DIR
 # COPY ./php-fpm.conf /usr/local/etc/
 
-# Composer
-RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
-  && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
-  && php composer-setup.php  --filename=composer --install-dir=/usr/local/bin/ \
-  && php -r "unlink('composer-setup.php');"
+# Composer programmatically: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
+RUN EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)" \
+  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+  && ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" \
+  && if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then \
+    >&2 echo 'ERROR: Invalid installer checksum' \
+    && rm composer-setup.php \
+    && exit 1; \
+  fi \
+  && php composer-setup.php --quiet --filename=composer --install-dir=/usr/local/bin/ \
+  && RESULT=$? \
+  && rm composer-setup.php \
+  && exit $RESULT
+
+# Composer v1.10.10
+# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+#   && php -r "if (hash_file('sha384', 'composer-setup.php') === '8a6138e2a05a8c28539c9f0fb361159823655d7ad2deecb371b04a83966c61223adc522b0189079e3e9e277cd72b8897') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
+#   && php composer-setup.php  --filename=composer --install-dir=/usr/local/bin/ \
+#   && php -r "unlink('composer-setup.php');"
 
   # 把 composer 全域包進 path
 ENV PATH=$PATH:~/.composer/vendor/bin
@@ -35,7 +49,7 @@ ENV PATH=$PATH:~/.composer/vendor/bin
 # Laravel
 # RUN composer global require laravel/installer
 
-# Symfony
+# Symfony-cli
 RUN wget https://get.symfony.com/cli/installer -O - | bash \
   && mv /root/.symfony/bin/symfony /usr/local/bin/symfony
 
